county_fips_lookup = {
    'Adams': {'COUNTY NO': '01', 'ALPHABETIC CODE': 'ADA', 'DISTRICT': '09', 'FIPS CODE': '01'},
    'Allen': {'COUNTY_CODE': '02', 'ALPHABETIC CODE': 'ALL', 'DISTRICT': '01', 'FIPS_CODE': '03'},
    'Ashland': {'COUNTY_CODE': '03', 'ALPHABETIC CODE': 'ASD', 'DISTRICT': '03', 'FIPS_CODE': '05'},
    'Ashtabula': {'COUNTY_CODE': '04', 'ALPHABETIC CODE': 'ASH', 'DISTRICT': '04', 'FIPS_CODE': '07'},
    'Athens': {'COUNTY_CODE': '05', 'ALPHABETIC CODE': 'ATH', 'DISTRICT': '10', 'FIPS_CODE': '09'},
    'Auglaize': {'COUNTY_CODE': '06', 'ALPHABETIC CODE': 'AUG', 'DISTRICT': '07', 'FIPS_CODE': '11'},
    'Belmont': {'COUNTY_CODE': '07', 'ALPHABETIC CODE': 'BEL', 'DISTRICT': '11', 'FIPS_CODE': '13'},
    'Brown': {'COUNTY_CODE': '08', 'ALPHABETIC CODE': 'BRO', 'DISTRICT': '09', 'FIPS_CODE': '15'},
    'Butler': {'COUNTY_CODE': '09', 'ALPHABETIC CODE': 'BUT', 'DISTRICT': '08', 'FIPS_CODE': '17'},
    'Carroll': {'COUNTY_CODE': '10', 'ALPHABETIC CODE': 'CAR', 'DISTRICT': '11', 'FIPS_CODE': '19'},
    'Champaign': {'COUNTY_CODE': '11', 'ALPHABETIC CODE': 'CHP', 'DISTRICT': '07', 'FIPS_CODE': '21'},
    'Clark': {'COUNTY_CODE': '12', 'ALPHABETIC CODE': 'CLA', 'DISTRICT': '07', 'FIPS_CODE': '23'},
    'Clermont': {'COUNTY_CODE': '13', 'ALPHABETIC CODE': 'CLE', 'DISTRICT': '08', 'FIPS_CODE': '25'},
    'Clinton': {'COUNTY_CODE': '14', 'ALPHABETIC CODE': 'CLI', 'DISTRICT': '08', 'FIPS_CODE': '27'},
    'Columbiana': {'COUNTY_CODE': '15', 'ALPHABETIC CODE': 'COL', 'DISTRICT': '11', 'FIPS_CODE': '29'},
    'Coshocton': {'COUNTY_CODE': '16', 'ALPHABETIC CODE': 'COS', 'DISTRICT': '05', 'FIPS_CODE': '31'},
    'Crawford': {'COUNTY_CODE': '17', 'ALPHABETIC CODE': 'CRA', 'DISTRICT': '03', 'FIPS_CODE': '33'},
    'Cuyahoga': {'COUNTY_CODE': '18', 'ALPHABETIC CODE': 'CUY', 'DISTRICT': '12', 'FIPS_CODE': '35'},
    'Darke': {'COUNTY_CODE': '19', 'ALPHABETIC CODE': 'DAR', 'DISTRICT': '07', 'FIPS_CODE': '37'},
    'Defiance': {'COUNTY_CODE': '20', 'ALPHABETIC CODE': 'DEF', 'DISTRICT': '01', 'FIPS_CODE': '39'},
    'Delaware': {'COUNTY_CODE': '21', 'ALPHABETIC CODE': 'DEL', 'DISTRICT': '06', 'FIPS_CODE': '41'},
    'Erie': {'COUNTY_CODE': '22', 'ALPHABETIC CODE': 'ERI', 'DISTRICT': '03', 'FIPS_CODE': '43'},
    'Fairfield': {'COUNTY_CODE': '23', 'ALPHABETIC CODE': 'FAI', 'DISTRICT': '05', 'FIPS_CODE': '45'},
    'Fayette': {'COUNTY_CODE': '24', 'ALPHABETIC CODE': 'FAY', 'DISTRICT': '06', 'FIPS_CODE': '47'},
    'Franklin': {'COUNTY_CODE': '25', 'ALPHABETIC CODE': 'FRA', 'DISTRICT': '06', 'FIPS_CODE': '49'},
    'Fulton': {'COUNTY_CODE': '26', 'ALPHABETIC CODE': 'FUL', 'DISTRICT': '02', 'FIPS_CODE': '51'},
    'Gallia': {'COUNTY_CODE': '27', 'ALPHABETIC CODE': 'GAL', 'DISTRICT': '10', 'FIPS_CODE': '53'},
    'Geauga': {'COUNTY_CODE': '28', 'ALPHABETIC CODE': 'GEA', 'DISTRICT': '12', 'FIPS_CODE': '55'},
    'Greene': {'COUNTY_CODE': '29', 'ALPHABETIC CODE': 'GRE', 'DISTRICT': '08', 'FIPS_CODE': '57'},
    'Guernsey': {'COUNTY_CODE': '30', 'ALPHABETIC CODE': 'GUE', 'DISTRICT': '05', 'FIPS_CODE': '59'},
    'Hamilton': {'COUNTY_CODE': '31', 'ALPHABETIC CODE': 'HAM', 'DISTRICT': '08', 'FIPS_CODE': '61'},
    'Hancock': {'COUNTY_CODE': '32', 'ALPHABETIC CODE': 'HAN', 'DISTRICT': '01', 'FIPS_CODE': '63'},
    'Hardin': {'COUNTY_CODE': '33', 'ALPHABETIC CODE': 'HAR', 'DISTRICT': '01', 'FIPS_CODE': '65'},
    'Harrison': {'COUNTY_CODE': '34', 'ALPHABETIC CODE': 'HAS', 'DISTRICT': '11', 'FIPS_CODE': '67'},
    'Henry': {'COUNTY_CODE': '35', 'ALPHABETIC CODE': 'HEN', 'DISTRICT': '02', 'FIPS_CODE': '69'},
    'Highland': {'COUNTY_CODE': '36', 'ALPHABETIC CODE': 'HIG', 'DISTRICT': '09', 'FIPS_CODE': '71'},
    'Hocking': {'COUNTY_CODE': '37', 'ALPHABETIC CODE': 'HOC', 'DISTRICT': '10', 'FIPS_CODE': '73'},
    'Holmes': {'COUNTY_CODE': '38', 'ALPHABETIC CODE': 'HOL', 'DISTRICT': '11', 'FIPS_CODE': '75'},
    'Huron': {'COUNTY_CODE': '39', 'ALPHABETIC CODE': 'HUR', 'DISTRICT': '03', 'FIPS_CODE': '77'},
    'Jackson': {'COUNTY_CODE': '40', 'ALPHABETIC CODE': 'JAC', 'DISTRICT': '09', 'FIPS_CODE': '79'},
    'Jefferson': {'COUNTY_CODE': '41', 'ALPHABETIC CODE': 'JEF', 'DISTRICT': '11', 'FIPS_CODE': '81'},
    'Knox': {'COUNTY_CODE': '42', 'ALPHABETIC CODE': 'KNO', 'DISTRICT': '05', 'FIPS_CODE': '83'},
    'Lake': {'COUNTY_CODE': '43', 'ALPHABETIC CODE': 'LAK', 'DISTRICT': '12', 'FIPS_CODE': '85'},
    'Lawrence': {'COUNTY_CODE': '44', 'ALPHABETIC CODE': 'LAW', 'DISTRICT': '09', 'FIPS_CODE': '87'},
    'Licking': {'COUNTY_CODE': '45', 'ALPHABETIC CODE': 'LIC', 'DISTRICT': '05', 'FIPS_CODE': '89'},
    'Logan': {'COUNTY_CODE': '46', 'ALPHABETIC CODE': 'LOG', 'DISTRICT': '07', 'FIPS_CODE': '91'},
    'Lorain': {'COUNTY_CODE': '47', 'ALPHABETIC CODE': 'LOR', 'DISTRICT': '03', 'FIPS_CODE': '93'},
    'Lucas': {'COUNTY_CODE': '48', 'ALPHABETIC CODE': 'LUC', 'DISTRICT': '02', 'FIPS_CODE': '95'},
    'Madison': {'COUNTY_CODE': '49', 'ALPHABETIC CODE': 'MAD', 'DISTRICT': '06', 'FIPS_CODE': '97'},
    'Mahoning': {'COUNTY_CODE': '50', 'ALPHABETIC CODE': 'MAH', 'DISTRICT': '04', 'FIPS_CODE': '99'},
    'Marion': {'COUNTY_CODE': '51', 'ALPHABETIC CODE': 'MAR', 'DISTRICT': '06', 'FIPS_CODE': '101'},
    'Medina': {'COUNTY_CODE': '52', 'ALPHABETIC CODE': 'MED', 'DISTRICT': '03', 'FIPS_CODE': '103'},
    'Meigs': {'COUNTY_CODE': '53', 'ALPHABETIC CODE': 'MEG', 'DISTRICT': '10', 'FIPS_CODE': '105'},
    'Mercer': {'COUNTY_CODE': '54', 'ALPHABETIC CODE': 'MER', 'DISTRICT': '07', 'FIPS_CODE': '107'},
    'Miami': {'COUNTY_CODE': '55', 'ALPHABETIC CODE': 'MIA', 'DISTRICT': '07', 'FIPS_CODE': '109'},
    'Monroe': {'COUNTY_CODE': '56', 'ALPHABETIC CODE': 'MOE', 'DISTRICT': '10', 'FIPS_CODE': '111'},
    'Montgomery': {'COUNTY_CODE': '57', 'ALPHABETIC CODE': 'MOT', 'DISTRICT': '07', 'FIPS_CODE': '113'},
    'Morgan': {'COUNTY_CODE': '58', 'ALPHABETIC CODE': 'MOR', 'DISTRICT': '10', 'FIPS_CODE': '115'},
    'Morrow': {'COUNTY_CODE': '59', 'ALPHABETIC CODE': 'MRW', 'DISTRICT': '06', 'FIPS_CODE': '117'},
    'Muskingum': {'COUNTY_CODE': '60', 'ALPHABETIC CODE': 'MUS', 'DISTRICT': '05', 'FIPS_CODE': '119'},
    'Noble': {'COUNTY_CODE': '61', 'ALPHABETIC CODE': 'NOB', 'DISTRICT': '10', 'FIPS_CODE': '121'},
    'Ottawa': {'COUNTY_CODE': '62', 'ALPHABETIC CODE': 'OTT', 'DISTRICT': '02', 'FIPS_CODE': '123'},
    'Paulding': {'COUNTY_CODE': '63', 'ALPHABETIC CODE': 'PAU', 'DISTRICT': '01', 'FIPS_CODE': '125'},
    'Perry': {'COUNTY_CODE': '64', 'ALPHABETIC CODE': 'PER', 'DISTRICT': '05', 'FIPS_CODE': '127'},
    'Pickaway': {'COUNTY_CODE': '65', 'ALPHABETIC CODE': 'PIC', 'DISTRICT': '06', 'FIPS_CODE': '129'},
    'Pike': {'COUNTY_CODE': '66', 'ALPHABETIC CODE': 'PIK', 'DISTRICT': '09', 'FIPS_CODE': '131'},
    'Portage': {'COUNTY_CODE': '67', 'ALPHABETIC CODE': 'POR', 'DISTRICT': '04', 'FIPS_CODE': '133'},
    'Preble': {'COUNTY_CODE': '68', 'ALPHABETIC CODE': 'PRE', 'DISTRICT': '08', 'FIPS_CODE': '135'},
    'Putnam': {'COUNTY_CODE': '69', 'ALPHABETIC CODE': 'PUT', 'DISTRICT': '01', 'FIPS_CODE': '137'},
    'Richland': {'COUNTY_CODE': '70', 'ALPHABETIC CODE': 'RIC', 'DISTRICT': '03', 'FIPS_CODE': '139'},
    'Ross': {'COUNTY_CODE': '71', 'ALPHABETIC CODE': 'ROS', 'DISTRICT': '09', 'FIPS_CODE': '141'},
    'Sandusky': {'COUNTY_CODE': '72', 'ALPHABETIC CODE': 'SAN', 'DISTRICT': '02', 'FIPS_CODE': '143'},
    'Scioto': {'COUNTY_CODE': '73', 'ALPHABETIC CODE': 'SCI', 'DISTRICT': '09', 'FIPS_CODE': '145'},
    'Seneca': {'COUNTY_CODE': '74', 'ALPHABETIC CODE': 'SEN', 'DISTRICT': '02', 'FIPS_CODE': '147'},
    'Shelby': {'COUNTY_CODE': '75', 'ALPHABETIC CODE': 'SHE', 'DISTRICT': '07', 'FIPS_CODE': '149'},
    'Stark': {'COUNTY_CODE': '76', 'ALPHABETIC CODE': 'STA', 'DISTRICT': '04', 'FIPS_CODE': '151'},
    'Summit': {'COUNTY_CODE': '77', 'ALPHABETIC CODE': 'SUM', 'DISTRICT': '04', 'FIPS_CODE': '153'},
    'Trumbull': {'COUNTY_CODE': '78', 'ALPHABETIC CODE': 'TRU', 'DISTRICT': '11', 'FIPS_CODE': '155'},
    'Tuscarawas': {'COUNTY_CODE': '79', 'ALPHABETIC CODE': 'TUS', 'DISTRICT': '11', 'FIPS_CODE': '157'},
    'Union': {'COUNTY_CODE': '80', 'ALPHABETIC CODE': 'UNI', 'DISTRICT': '06', 'FIPS_CODE': '159'},
    'Van_Wert': {'COUNTY_CODE': '81', 'ALPHABETIC CODE': 'VAN', 'DISTRICT':'01', 'FIPS_CODE': '161'},
    'Vinton': {'COUNTY_CODE': '82', 'ALPHABETIC CODE': 'VIN', 'DISTRICT': '10', 'FIPS_CODE': '163'},
    'Warren': {'COUNTY_CODE': '83', 'ALPHABETIC CODE': 'WAR', 'DISTRICT': '08', 'FIPS_CODE': '165'},
    'Washington': {'COUNTY_CODE': '84', 'ALPHABETIC CODE': 'WAS', 'DISTRICT': '10', 'FIPS_CODE': '167'},
    'Wayne': {'COUNTY_CODE': '85', 'ALPHABETIC CODE': 'WAY', 'DISTRICT': '03', 'FIPS_CODE': '169'},
    'Williams': {'COUNTY_CODE': '86', 'ALPHABETIC CODE': 'WIL', 'DISTRICT': '02', 'FIPS_CODE': '171'},
    'Wood': {'COUNTY_CODE': '87', 'ALPHABETIC CODE': 'WOO', 'DISTRICT': '02', 'FIPS_CODE': '173'},
    'Wyandot': {'COUNTY_CODE': '88', 'ALPHABETIC CODE': 'WYA', 'DISTRICT': '01', 'FIPS_CODE': '175'},
}

fhwa_43a = {
    '0': 'Other',
    '1': 'Concrete',
    '2': 'Concrete (Continuous)',
    '3': 'Steel',
    '4': 'Steel (Continuous)',
    '5': 'Prestressed/Post-Tensioned Concrete',
    '6': 'Prestressed/Post-Tensioned Concrete (Continuous)',
    '7': 'Wood or Timber',
    '8': 'Masonry',
    '9': 'Cast Iron, Aluminum, or Wrought Iron',
}

fhwa_43b = {
    '01': 'Slab',
    '02': 'Stringer/Multi-beam or Girder',
    '03': 'Girder and Floorbeam System',
    '04': 'Tee Beam',
    '05': 'Box Beam or Girders - Multiple',
    '06': 'Box Beam or Girders - Single or Spread',
    '07': 'Frame (except frame culverts)',
    '08': 'Orthotropic',
    '09': 'Truss - Deck',
    '10': 'Truss - Through',
    '11': 'Arch - Deck',
    '12': 'Arch - Through',
    '13': 'Suspension',
    '14': 'Stayed Girder',
    '15': 'Movable - Lift',
    '16': 'Movable - Bascule',
    '17': 'Movable - Swing',
    '18': 'Tunnel',
    '19': 'Culvert (includes frame culverts)',
    '20': 'Mixed Types (can only be used in approach spans [item 44])',
    '21': 'Segmental Box Girder',
    '22': 'Channel Beam',
    '00': 'Other',
}

ohio_43c = {
    '1': 'Pony Truss',
    '2': 'Through Girder',
    '3': 'Filled Arch',
    'N': 'Not Applicable'
}

ohio_107 = {
    '1': 'Jack Arch',
    '2': 'Slab prestressed in both directions',
    '3': 'Slab prestressed longitudinally only',
    '4': 'Slab prestressed transverse only',
    '5': 'Prestressed slab on beams'
}

ohio_108 = {
    '1': 'Super Plasticized',
    '2': 'MicroSilica',
    '3': 'Chip and Seal',
    '4': 'Polyester',
    'N': 'Not Applicable'
}

ohio_482 = {
    '1': 'Red lead',
    '2': 'Unpainted Weathered Steel',
    '3': 'Paint System A',
    '4': 'Paint System B',
    '5': 'Paint System OZEU',
    '6': 'Galvanized',
    '7': 'Metalized (Alum/Zinc)',
    '8': 'Paint System A with intermediate tie coat',
    '9': 'Paint System IZEU',
    '0': 'Other Paint',
    'A': 'EEU',
    'B': 'Epoxy – Urethane sealers',
    'C': 'Non-Epoxy sealers',
    'N': 'None or Not Applicable',
    'U': 'Unknown Sealant',
}
